#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
30212017 [MVP1] 单弹直线右移 — 最简心智模型验证技能 (2026-05-11)

设计意图（接力 GATE-1 用户拍板）：
    PoC 主目标：验证"OnTick init / REPEAT 每帧改子弹自身位置"的整套链路是否真的跑得通。
    没有圆周 / 没有数学 / 没有伤害 / 没有特效 — 只看 1 颗子弹是否每帧右移。

流程：
    1. 抬手 → 创建 1 颗锚点空子弹 (caster 位置 / Speed=0)
    2. 子弹 AfterBorn → OnTick REPEAT (60 帧 / interval=1 帧)
    3. 每帧 → 子弹自身 PosX += 5
    4. 60 帧后 → 子弹自然销毁 (LastTime=60 / LifeFlag=1)

10 节点 ID 段位 (用户拍板)：
    ┌────────────┬───────────────────────┬─────────────┐
    │ ID         │ 类型                  │ 作用         │
    ├────────────┼───────────────────────┼─────────────┤
    │ 30212017   │ SkillConfigNode       │ 顶层技能配置 │
    │ 302120170  │ BulletConfigNode      │ 锚点空子弹   │
    │ 302120171  │ TSET_CREATE_BULLET    │ 抬手创建子弹 │
    │ 302120172  │ ModelConfigNode       │ 空模型 ID=4  │
    │ 302120173  │ TSET_ORDER_EXECUTE    │ OnTick init  │
    │ 302120174  │ TSET_REPEAT_EXECUTE   │ 每帧重复     │
    │ 302120175  │ TSET_ORDER_EXECUTE    │ 每帧 ORDER 链│
    │ 302120176  │ TSET_ADD_ENTITY_ATTR_VALUE │ PosX +=5│
    └────────────┴───────────────────────┴─────────────┘

GATE-0.5 grep 真实样本得到的关键事实（订正前几轮认知）：
- TPT_COMMON_PARAM(PT=5) Value=1 = 释放者 caster (来源: AIGenerate/skill-patterns.md L149)
- TBN_POS_X = 59 / TBN_POS_Y = 60 / TBN_FACE_DIR = 91 (来源: common.nothotfix.cs L4279-L4407)
- TBN_ENTITY_ID = 75 (实体实例ID — 这是属性枚举值，不是 caster) (L4343)
- TSET_CREATE_BULLET 共 15 个 Params，关键：
    [0]子弹ID [1]角度 [2]位置X [3]位置Y [4]创建者单位
    (来源: SkillEffectConfig_ParamsAutoGenerated.cs L164-L184)
- TSET_REPEAT_EXECUTE 共 10 个 Params:
    [0]间隔帧数 [1]执行次数 [2]立即 [3]技能效果ID [4]筛选 ...
    (来源: 同文件 L53-L67)
- TSET_ADD_ENTITY_ATTR_VALUE: [0]单位 [1]属性枚举 [2]变化值
    SkillEffectType=71 (L1225-L1232)

TableTash:
- SkillEffect: 0CFA05568A66FEA1DF3BA6FE40DB7080
- BulletConfig: 1955259A502D05C224412EDD4D1CD75D
- SkillConfig:  1B07683FF8D5DAE7F1CB4F2B3F22A2C7
- ModelConfig:  待补 / 用真实样本中的值

Sticky Note v3 5 段：作用 / 流程 / 特殊条件 / 参数 / 联动
"""
from __future__ import annotations
import json
import sys
import uuid
from pathlib import Path

PROJ = Path(r"<<PROJECT_ROOT_WIN>>")
OUTPUT = PROJ / "<<SKILLGRAPH_JSONS_ROOT>>宗门技能/木宗门技能/SkillGraph_30212017【MVP1】单弹直线右移.json"

# ===== 10 节点 ID（用户 GATE-1 拍板，不准动）=====
SKILL_ID            = 30212017
BULLET_CFG_ID       = 302120170
CREATE_BULLET_ID    = 302120171
MODEL_CFG_ID        = 302120172
ONTICK_INIT_ID      = 302120173    # ⭐ BulletConfig.AfterBorn 指向这里
ONTICK_REPEAT_ID    = 302120174
FRAME_ORDER_ID      = 302120175
ADD_POSX_ID         = 302120176

# ===== TableTash =====
TASH_SKILL_EFFECT  = "0CFA05568A66FEA1DF3BA6FE40DB7080"
TASH_BULLET_CONFIG = "1955259A502D05C224412EDD4D1CD75D"
TASH_SKILL_CONFIG  = "1B07683FF8D5DAE7F1CB4F2B3F22A2C7"
TASH_MODEL_CONFIG  = "8B85FB7DAB94EE38C45C2DDA5A8DCD79"   # 占位 / 30212010 中 ModelConfigNode 没看到 / 编辑器会校核

# ===== TSkillEffectType =====
ET_ORDER  = 1
ET_REPEAT = 3
ET_CREATE_BULLET = 8
ET_ADD_ENTITY_ATTR_VALUE = 71

# ===== TParamType =====
PT_NULL = 0          # 常量直接值 / 子节点 ID 引用
PT_ATTR = 1          # 属性引用
PT_FUNC_RET = 2      # 函数返回引用
PT_COMMON_PARAM = 5  # 常用数值参数（V=1 = caster）

# ===== TBattleNumeric =====
TBN_POS_X = 59
TBN_POS_Y = 60
TBN_FACE_DIR = 91

# ===== TPT_COMMON_PARAM 实参 =====
COMMON_CASTER = 1  # 施法者自身 (skill-patterns.md L149 证据)


def new_guid() -> str:
    return str(uuid.uuid4())


def make_param(value: int, param_type: int = PT_NULL, factor: int = 0) -> dict:
    return {"Value": value, "ParamType": param_type, "Factor": factor}


def make_node(rid: int, cls: str, node_id: int, payload: dict, position: tuple,
              desc: str, tash: str, table_for_cls: str, extra_data: dict | None = None) -> dict:
    """构造一个标准节点字典 (rid + type + data + ConfigJson 内嵌 payload)"""
    data = {
        "GUID": new_guid(),
        "computeOrder": rid - 1000,
        "position": {
            "serializedVersion": "2",
            "x": float(position[0]), "y": float(position[1]),
            "width": 320.0, "height": 200.0,
        },
        "expanded": False, "debug": False, "nodeLock": False, "visible": True,
        "hideChildNodes": False, "hidePos": {"x": 0.0, "y": 0.0}, "hideCounter": 0,
        "ID": node_id,
        "Desc": desc,
        "paramVersion": 0,
        "templateParamVersion": 0,
        "IsTemplate": False, "TemplateFlags": 0,
        "TemplateParams": [], "TemplateParamsDesc": [], "TemplateParamsCustomAdd": False,
        "TableTash": tash,
        "ConfigJson": json.dumps(payload, ensure_ascii=False, separators=(",", ":")),
        "Config2ID": f"{table_for_cls}_{node_id}",
    }
    if extra_data:
        data.update(extra_data)
    return {
        "rid": rid,
        "type": {"class": cls, "ns": "NodeEditor", "asm": "NodeEditor"},
        "data": data,
    }


def build():
    refs = []

    # ===== 节点 1: ModelConfigNode (Model ID = 4 / 空子弹专属) =====
    # PostMortem #024：创建空子弹/锚点子弹时 Model 必填 4，不要填 0
    model_payload = {
        "ID": MODEL_CFG_ID,
        "ResPath": "Assets/PackRes/Effect/Empty/Empty.prefab",  # 占位 / 编辑器同步会校核
        "Scale": 100,
        "Effect": 0,
    }
    refs.append(make_node(
        rid=1001,
        cls="ModelConfigNode",
        node_id=MODEL_CFG_ID,
        payload=model_payload,
        position=(800.0, 400.0),
        desc="空模型占位 (BulletConfig.Model 必填非 0 / Model=4 是空模型枚举)",
        tash=TASH_MODEL_CONFIG,
        table_for_cls="ModelConfig",
    ))

    # ===== 节点 2: BulletConfigNode (锚点空子弹 / Speed=0 / AfterBorn → OnTick init) =====
    bullet_payload = {
        "ID": BULLET_CFG_ID,
        "FlyType": 0,                        # 0 = 直线（不重要，因为 Speed=0）
        "ChaseTargetEnemy_AttachPos": 0,
        "ChaseTargetEnemy_FaceToTarget": False,
        "ChaseTargetEnemy_PitchFaceToTarget": False,
        "IsAiEscape": False,
        "AngleAdjustType": 0,
        "Speed": 0,                          # 位移完全由 OnTick 接管
        "AcceSpeed": 0,
        "MaxSpeed": 0,
        "TurnSpeed": 0,
        "TurnAcceSpeed": 0,
        "MaxTurnSpeed": 0,
        "IsCloseTurnAutoHit": False,
        "PitchTurnSpeed": 0,
        "PitchTurnAcceSpeed": 0,
        "PitchMaxTurnSpeed": 0,
        "IsOpenPhysicalReflect": False,
        "PhysicalReflectCount": 0,
        "PhysicalReflectEndActionType": 0,
        "TracePathType": 0,
        "TracePathParams": [],
        "LastTime": 60,                      # 60 帧 = 2 秒
        "delayDestroyTime": 0,
        "DestroyWhenCreatorDie": False,
        "Hp": 0,
        "ATK": 0,
        "BeforeBornSkillEffectExecuteInfo": {"SelectConfigID": 0, "SkillEffectConfigID": 0},
        "AfterBornSkillEffectExecuteInfo": {"SelectConfigID": 0, "SkillEffectConfigID": ONTICK_INIT_ID},  # ⭐ 关键
        "DieSkillEffectExecuteInfo": {"SelectConfigID": 0, "SkillEffectConfigID": 0},
        "Model": 4,                          # PostMortem #024：空子弹必填 4 / 不能填 0
        "ModelBaseScalePercent": 100,
        "ChainModel": 0,
        "ChainModelScalePercent": 0,
        "ChainTilingFactor": 0,
        "DisappearEffect": 0,
        "LifeFlag": 1,                       # 1 = 定时销毁
        "MaxDistance": 0,
        "TrackEntityNoTargetSkillEffectConfigID": 0,
        "IsDieKeepMove": False,
        "Flags": 0,
    }
    refs.append(make_node(
        rid=1002,
        cls="BulletConfigNode",
        node_id=BULLET_CFG_ID,
        payload=bullet_payload,
        position=(400.0, 400.0),
        desc=(
            f"锚点空子弹 / Model=4 (空 / PostMortem #024)\n"
            f"Speed=0 全部基础位移参数关闭\n"
            f"LastTime=60 帧 / LifeFlag=1 (定时销毁)\n"
            f"⭐ AfterBorn={ONTICK_INIT_ID} → 触发 OnTick init"
        ),
        tash=TASH_BULLET_CONFIG,
        table_for_cls="BulletConfig",
    ))

    # ===== 节点 3: TSET_ADD_ENTITY_ATTR_VALUE (子弹自身 PosX += 5) =====
    # Params: [0]单位 [1]属性枚举 [2]变化值
    # 单位 = "执行 OnTick 的 entity" = 这颗子弹自身 / 用 caster 语义在子弹上下文中等于子弹自己
    # ⚠️ 注意：在 BulletConfig.AfterBorn 触发的 OnTick 链里，"caster (V=1 PT=5)" 是这颗子弹本身，
    # 不是技能释放者 (skill-patterns.md L149 caster 语义在 entity 上下文中切换)。
    add_posx_payload = {
        "ID": ADD_POSX_ID,
        "SkillEffectType": ET_ADD_ENTITY_ATTR_VALUE,
        "Params": [
            make_param(COMMON_CASTER, PT_COMMON_PARAM),  # [0] 单位 = 子弹自身 (caster in bullet ctx)
            make_param(TBN_POS_X, PT_NULL),               # [1] 属性 = TBN_POS_X = 59
            make_param(5, PT_NULL),                       # [2] 变化值 = +5
        ],
    }
    refs.append(make_node(
        rid=1003,
        cls="TSET_ADD_ENTITY_ATTR_VALUE",
        node_id=ADD_POSX_ID,
        payload=add_posx_payload,
        position=(2400.0, 600.0),
        desc=(
            "[每帧] 子弹自身 PosX += 5\n"
            "Param[0]: V=1 PT=5 (TPT_COMMON_PARAM=caster in bullet ctx = 子弹本身)\n"
            "Param[1]: V=59 PT=0 (TBN_POS_X 位置X)\n"
            "Param[2]: V=5 PT=0 (delta 5 单位/帧)"
        ),
        tash=TASH_SKILL_EFFECT,
        table_for_cls="SkillEffectConfig",
        extra_data={"SkillEffectType": ET_ADD_ENTITY_ATTR_VALUE},
    ))

    # ===== 节点 4: TSET_ORDER_EXECUTE (每帧 ORDER 链 / 当前只调一个 ADD_POSX) =====
    frame_order_payload = {
        "ID": FRAME_ORDER_ID,
        "SkillEffectType": ET_ORDER,
        "Params": [
            make_param(ADD_POSX_ID, PT_NULL),  # 唯一子节点 = ADD_POSX
        ],
    }
    refs.append(make_node(
        rid=1004,
        cls="TSET_ORDER_EXECUTE",
        node_id=FRAME_ORDER_ID,
        payload=frame_order_payload,
        position=(2000.0, 600.0),
        desc="[每帧 ORDER] 当前只链入 ADD_POSX (后续可扩展)",
        tash=TASH_SKILL_EFFECT,
        table_for_cls="SkillEffectConfig",
        extra_data={"SkillEffectType": ET_ORDER},
    ))

    # ===== 节点 5: TSET_REPEAT_EXECUTE (60 帧 / interval=1 / 执行 FRAME_ORDER) =====
    # Params: [0]间隔 [1]次数 [2]立即 [3]效果ID [4]筛选 [5]中断 [6]死后续 [7]结束效果 [8]战后续 [9]受急速
    ontick_repeat_payload = {
        "ID": ONTICK_REPEAT_ID,
        "SkillEffectType": ET_REPEAT,
        "Params": [
            make_param(1, PT_NULL),                 # [0] interval = 1 帧
            make_param(60, PT_NULL),                # [1] count = 60 次
            make_param(0, PT_NULL),                 # [2] 立即执行 = 否
            make_param(FRAME_ORDER_ID, PT_NULL),    # [3] effect ID
            make_param(0, PT_NULL),                 # [4] 筛选 (无 / 沿用原始)
            make_param(0, PT_NULL),                 # [5] 中断
            make_param(0, PT_NULL),                 # [6] 单位死后续
            make_param(0, PT_NULL),                 # [7] 结束效果
            make_param(0, PT_NULL),                 # [8] 战斗结束续
            make_param(0, PT_NULL),                 # [9] 受急速影响
        ],
    }
    refs.append(make_node(
        rid=1005,
        cls="TSET_REPEAT_EXECUTE",
        node_id=ONTICK_REPEAT_ID,
        payload=ontick_repeat_payload,
        position=(1600.0, 600.0),
        desc=(
            "[OnTick REPEAT] interval=1 / count=60\n"
            f"每帧调 ORDER {FRAME_ORDER_ID} / 60 帧后停"
        ),
        tash=TASH_SKILL_EFFECT,
        table_for_cls="SkillEffectConfig",
        extra_data={"SkillEffectType": ET_REPEAT},
    ))

    # ===== 节点 6: TSET_ORDER_EXECUTE (OnTick init 入口 / BulletConfig.AfterBorn 指向这里) =====
    ontick_init_payload = {
        "ID": ONTICK_INIT_ID,
        "SkillEffectType": ET_ORDER,
        "Params": [
            make_param(ONTICK_REPEAT_ID, PT_NULL),  # 唯一子节点 = REPEAT
        ],
    }
    refs.append(make_node(
        rid=1006,
        cls="TSET_ORDER_EXECUTE",
        node_id=ONTICK_INIT_ID,
        payload=ontick_init_payload,
        position=(1200.0, 600.0),
        desc=(
            f"[OnTick init / BulletConfig.AfterBorn 入口]\n"
            f"启动 REPEAT {ONTICK_REPEAT_ID}"
        ),
        tash=TASH_SKILL_EFFECT,
        table_for_cls="SkillEffectConfig",
        extra_data={"SkillEffectType": ET_ORDER},
    ))

    # ===== 节点 7: TSET_CREATE_BULLET (抬手创建 1 颗子弹) =====
    # Params: [0]子弹ID [1]角度 [2]位置X [3]位置Y [4]创建者 [5]offset右 [6]offset前
    #         [7]子子弹 [8]单位组 [9]射弹类 [10]初始SkillInstance [11]自定义模型
    #         [12]高度Z [13]初始仰角 [14]受急速影响
    # 角度 / 位置 X / 位置 Y / 创建者 → 全用 caster 默认（PT=1 ATTR 取 caster 自己当前数值）
    create_bullet_payload = {
        "ID": CREATE_BULLET_ID,
        "SkillEffectType": ET_CREATE_BULLET,
        "Params": [
            make_param(BULLET_CFG_ID, PT_NULL),       # [0] BulletConfig
            make_param(TBN_FACE_DIR, PT_ATTR),        # [1] 角度 = caster.face_dir
            make_param(TBN_POS_X, PT_ATTR),           # [2] 位置X = caster.posX
            make_param(TBN_POS_Y, PT_ATTR),           # [3] 位置Y = caster.posY
            make_param(COMMON_CASTER, PT_COMMON_PARAM),  # [4] 创建者 = caster
            make_param(0, PT_NULL),                   # [5] offset 右
            make_param(0, PT_NULL),                   # [6] offset 前
            make_param(0, PT_NULL),                   # [7] 是否子子弹
            make_param(0, PT_NULL),                   # [8] 单位组
            make_param(0, PT_NULL),                   # [9] 是否射弹类
            make_param(0, PT_NULL),                   # [10] 初始 SkillInstance
            make_param(0, PT_NULL),                   # [11] 自定义模型 (用 BulletConfig.Model)
            make_param(0, PT_NULL),                   # [12] 高度Z
            make_param(0, PT_NULL),                   # [13] 初始仰角
            make_param(0, PT_NULL),                   # [14] 受急速影响 = 否
        ],
    }
    refs.append(make_node(
        rid=1007,
        cls="TSET_CREATE_BULLET",
        node_id=CREATE_BULLET_ID,
        payload=create_bullet_payload,
        position=(0.0, 200.0),
        desc=(
            f"[抬手] 创建 1 颗 BulletConfig {BULLET_CFG_ID}\n"
            "位置 = caster 当前位置 (PosX/PosY/FaceDir 都用 PT=1 ATTR 取 caster 实时值)\n"
            "Param[4] V=1 PT=5 = caster (创建者)"
        ),
        tash=TASH_SKILL_EFFECT,
        table_for_cls="SkillEffectConfig",
        extra_data={"SkillEffectType": ET_CREATE_BULLET},
    ))

    # ===== 节点 8: SkillConfigNode (顶层 / 入口指向 CREATE_BULLET) =====
    skill_payload = {
        "ID": SKILL_ID,
        "SkillNameKey": 0,
        "SkillDescKey": 0,
        "SkillNameEditor": "[MVP1] 单弹直线右移",
        "SkillDescEditor": (
            "[PoC MVP1] 最简心智模型验证。释放后在 caster 位置生成 1 颗空子弹，"
            "自身 Speed=0，每帧通过 ADD_ENTITY_ATTR 给 PosX 加 5，60 帧后销毁。"
            "目的：验证 OnTick init / REPEAT 改子弹自身位置链路是否真跑通。"
        ),
        "Icon": "Skill/Pugong/PuGong_mu",
        "ElementType": 2,                    # 木
        "SkillSchoolResType": 0,
        "FeatureLabel": 0,
        "BDLabels": [],
        "SkillAITags": [],
        "DamageType": 1,                     # 物理 (无伤害但占位)
        "SkillMainType": 1,                  # 功法技
        "SkillSubType": 102,                 # 木宗门人阶奇术
        "MPCost": 0,
        "HunLiValue": 0,
        "SectXinfaEnergyValue": 0,
        "SkillCastFrame": 0,
        "SkillBufferStartFrame": 0,
        "SkillBufferFrame": 30,
        "SkillBaseDuration": 30,
        "SkillCastIsNotInterruptable": False,
        "IsSkillBufferFrameCanMove": False,
        "CdType": 1,
        "CdTime": 60,                        # 1 秒 CD (PoC 方便连测)
        "ComboCdList": [],
        "CDMaxStoreCount": 0,
        "SkillFixCdTime": 0,
        "SkillRange": 600,                   # 5 单位/帧 × 60 帧 = 300 单位 / 留 600 余量
        "SkillMinRange": 0,
        "AISkillRange": 600,
        "ExtraAlertRange": 0,
        "IsCloseChaseInAlertRange": True,
        "NeedTargetInRange": False,
        "IsSkillCastNoTargetInIdle": False,
        "Condition": 0,
        "AICastCondition": 0,
        "SkillEffectExecuteInfo": {"SelectConfigID": 0, "SkillEffectConfigID": CREATE_BULLET_ID},
        "SkillEffectPassiveExecuteInfo": {"SelectConfigID": 0, "SkillEffectConfigID": 0},
        "SkillEffectOnUnEquip": 0,
        "ChantCounterValuesList": [],
        "LGDamageValuesList": [],
        "SkillDamageTagsList": [],
        "SkillTagsList": [],
        "SkillTipsConditionSkillTagsList": [],
        "SkillGrowthDesc": "",
        "TalentKeyWord": [],
        "UseSkillSpeedDownValue": 0,
        "UseSkillSpeedDownTime": 0,
        "SkillIndicatorType": 0,             # 无指示器 (PoC)
        "SkillIndicatorParam": [],
        "SkillIndicatorParamTagConfigIds": [],
        "SkillIndicatorResParam": [],
        "SkillIndicatorResParamTagConfigIds": [],
        "LockEntityAfterUseSkillDuration": 0,
        "LockEntityPosTypeAfterUseSkill": 0,
        "SkillEffectOnSkillCastInterrupt": 0,
        "UseSkillForbidUpdateFaceDir": False,
        "UseType": 1,
        "ButtonUpConfig": 0,
        "InterruptConfig": 0,
        "ReActiveConfig": 0,
        "SkillQuality": 2,
        "IsPassiveSkillHideCD": False,
        "IsPassiveSkillNotRunByCD": False,
        "SkillProperty": 0,
        "SkillRangeTagConfigId": 0,
        "SkillMinRangeTagConfigId": 0,
        "SmartCastTargetBasePriority": 3,
        "SmartCastTargetCondTemplate": 1,
        "SmartCastTargetMonsterRankCond": [16, 15, 14, 13, 12, 11, 4, 5, 6, 0],
        "SmartCastTargetCampCond": [2],
        "SmartCastNoTargetIndicatorPos": 0,
        "SmartCastNoTargetCancelUse": False,
        "CastTargetCondTemplate": 1,
        "CastTargetMonsterRankCond": [16, 15, 14, 13, 12, 11, 4, 5, 6, 0],
        "CastTargetCampCond": [2],
        "IsHideContinueUseSkillHeadBar": False,
        "SkillPriority": 0,
        "EnhanceSkillBuffConfigID": 0,
        "StatisticsDamageAloneForSummon": False,
        "SkillXinfaType": 0,
    }
    refs.append(make_node(
        rid=1008,
        cls="SkillConfigNode",
        node_id=SKILL_ID,
        payload=skill_payload,
        position=(-400.0, 200.0),
        desc=(
            f"30212017 [MVP1] 单弹直线右移\n"
            f"主入口 SkillEffectConfigID={CREATE_BULLET_ID}\n"
            f"PoC：验证 OnTick init / REPEAT 链路"
        ),
        tash=TASH_SKILL_CONFIG,
        table_for_cls="SkillConfig",
    ))

    return refs


def make_sticky_notes() -> list:
    """v3 5 段：作用 / 流程 / 特殊条件 / 参数 / 联动"""
    content = (
        "[作用]\n"
        "MVP1 最简心智模型验证技能：释放后在 caster 当前位置生成 1 颗空子弹（无视觉模型 / 无伤害），"
        "通过 OnTick REPEAT 每帧给该子弹的 PosX 属性加 5 单位，连续执行 60 帧（约 2 秒）后子弹自然销毁。"
        "目的：验证 'BulletConfig.AfterBorn → OnTick ORDER → REPEAT → ADD_ENTITY_ATTR' 这条链路在"
        "宗门技能上下文里是否真的能驱动子弹位移。\n\n"

        "[流程]\n"
        "释放 SkillConfig 30212017\n"
        "  └→ TSET_CREATE_BULLET 302120171 [抬手]\n"
        "      └→ 在 caster 位置创建 BulletConfig 302120170\n"
        "          └→ AfterBorn (entity ctx) = OnTick init 302120173\n"
        "              └→ TSET_ORDER 302120173 [OnTick init]\n"
        "                  └→ TSET_REPEAT 302120174 (interval=1 / count=60)\n"
        "                      └→ 每帧调 TSET_ORDER 302120175 [frame chain]\n"
        "                          └→ TSET_ADD_ENTITY_ATTR_VALUE 302120176\n"
        "                              └→ 子弹自身 PosX += 5\n"
        "60 帧后\n"
        "  └→ 子弹 LastTime=60 / LifeFlag=1 自然销毁\n\n"

        "[特殊条件]\n"
        "- BulletConfig.Speed = 0 / 全部基础位移参数关闭 → 位移完全交给 OnTick 接管\n"
        "- BulletConfig.Model = 4 (空模型 / PostMortem #024：必填非 0)\n"
        "- BulletConfig.AfterBorn 必须 = OnTick init 节点 ID (本图 302120173)\n"
        "- ADD_ENTITY_ATTR Param[0] V=1 PT=5：在子弹 OnTick 上下文里 caster 语义 = 子弹自身\n"
        "  (这是和技能 ctx 的关键区别 / 用同样的 V=1 PT=5 在主技能里指释放者)\n"
        "- 不带任何伤害 / 不带 SkillTag / 不带任何指示器\n"
        "- 60 帧执行 / +5 单位/帧 = 总位移 300 单位 (≈ 3 米) / 主角面前直线\n"
        "- ⚠️ ADD_ENTITY_ATTR 改的是 PosX 属性 / 是否触发 entity 位置同步未实测 / 这正是 PoC 要验证的事\n\n"

        "[参数]\n"
        "- BulletConfig 数量 = 1\n"
        "- BulletConfig.Speed = 0\n"
        "- BulletConfig.LastTime = 60 帧\n"
        "- BulletConfig.LifeFlag = 1 (定时销毁)\n"
        "- BulletConfig.Model = 4 (空)\n"
        "- TSET_REPEAT.interval = 1 帧\n"
        "- TSET_REPEAT.count = 60 次\n"
        "- TSET_ADD_ENTITY_ATTR.delta = +5 单位/帧\n"
        "- TSET_ADD_ENTITY_ATTR.attr = TBN_POS_X (= 59)\n"
        "- SkillCastFrame = 0 / SkillBufferFrame = 30 / SkillBaseDuration = 30 / CdTime = 60\n"
        "- SkillRange = 600 (留余量 / 实际位移 300)\n\n"

        "[联动]\n"
        "- ID 段位 30212017 顶层 / 7 个子节点 302120170-176\n"
        "- 不依赖任何外部模板 / 不依赖任何外部 SkillEffect / 完全 self-contained\n"
        "- 配套 30212016 v08 失败路线已 archive (备份在 _archive/30212016_v08_failed_route/)\n"
        "- 实测通过后 → 阶段 2 在本图基础上加 SkillTag 8 颗子弹圆周分布 + 旋转扩张\n"
        "- 首次 Ctrl+R 后必须在 SkillEditor 打开本技能 → 点 '同步数据' 让 30212017 / 302120170-176 进运行时表"
    )
    return [{
        "GUID": new_guid(),
        "position": {
            "serializedVersion": "2",
            "x": -1200.0, "y": -400.0,
            "width": 800.0, "height": 1300.0,
        },
        "title": "[MVP1] 30212017 单弹直线右移 — 心智模型 PoC 验证",
        "content": content,
    }]


def emit(refs: list, output_path: Path):
    """生成最终 SkillGraph JSON / 自动派生 PackedParamsOutput 边"""
    DYN_PORT = {"TSET_ORDER_EXECUTE", "TSET_REPEAT_EXECUTE"}
    SKIP_PARAM_DERIVE = {
        "SkillTagsConfigNode", "BulletConfigNode", "ModelConfigNode",
        "RefConfigBaseNode", "SkillConfigNode",
    }

    guid_of_id: dict[int, str] = {}
    for r in refs:
        rid_id = r["data"].get("ID")
        if rid_id is not None:
            guid_of_id[rid_id] = r["data"]["GUID"]

    edges = []
    for ref in refs:
        cls = ref["type"]["class"]
        if cls in SKIP_PARAM_DERIVE:
            continue
        try:
            cfg = json.loads(ref["data"]["ConfigJson"])
        except Exception:
            continue
        params = cfg.get("Params", [])
        is_dyn = cls in DYN_PORT
        for i, p in enumerate(params):
            if not isinstance(p, dict):
                continue
            v = p.get("Value", 0)
            pt = p.get("ParamType", 0)
            if pt in (1, 4, 5, 6) or v == 0:
                continue
            if not isinstance(v, int):
                continue
            target_guid = guid_of_id.get(v)
            if target_guid is None:
                continue
            if target_guid == ref["data"]["GUID"]:
                continue
            out_port = "0" if is_dyn else str(i)
            edges.append({
                "GUID": new_guid(),
                "inputNodeGUID": target_guid,
                "outputNodeGUID": ref["data"]["GUID"],
                "inputFieldName": "ID",
                "outputFieldName": "PackedParamsOutput",
                "inputPortIdentifier": "0",
                "outputPortIdentifier": out_port,
                "isVisible": True,
            })

    notes = make_sticky_notes()

    graph = {
        "serializationData": {
            "SerializedFormat": 0, "SerializedBytes": [],
            "ReferencedUnityObjects": [], "SerializedBytesString": "",
            "Prefab": {"instanceID": 0},
            "PrefabModificationsReferencedUnityObjects": [],
            "PrefabModifications": [], "SerializationNodes": [],
        },
        "nodes": [{"rid": r["rid"]} for r in refs],
        "edges": edges,
        "groups": [], "stackNodes": [],
        "pinnedElements": [{
            "position": {"serializedVersion": "2", "x": 0.0, "y": 0.0,
                          "width": 511.0, "height": 629.0},
            "opened": True,
            "editorType": {
                "serializedType": "NodeEditor.ConfigPinnedView, NodeEditor, "
                                  "Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"
            }
        }],
        "exposedParameters": [], "serializedParameterList": [],
        "stickyNotes": notes,
        "curTab": 0,
        "path": str(output_path).replace("\\", "/").replace(
            str(PROJ).replace("\\", "/") + "/", ""),
        "references": {"version": 2, "RefIds": refs},
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(graph, ensure_ascii=False, indent=4),
        encoding="utf-8"
    )
    return edges


def main():
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore
    refs = build()
    edges = emit(refs, OUTPUT)
    print(f"[OK] 30212017 [MVP1] 单弹直线右移 生成成功")
    print(f"  路径: {OUTPUT}")
    print(f"  节点数: {len(refs)}")
    print(f"  自动派生边数: {len(edges)}")
    print()
    print(f"  SkillConfig:    {SKILL_ID}")
    print(f"  BulletConfig:   {BULLET_CFG_ID}  (Model=4, AfterBorn → {ONTICK_INIT_ID})")
    print(f"  CREATE_BULLET:  {CREATE_BULLET_ID}")
    print(f"  ModelConfig:    {MODEL_CFG_ID}")
    print(f"  OnTick init:    {ONTICK_INIT_ID}")
    print(f"  OnTick REPEAT:  {ONTICK_REPEAT_ID}  (count=60, interval=1)")
    print(f"  Frame ORDER:    {FRAME_ORDER_ID}")
    print(f"  ADD_POSX:       {ADD_POSX_ID}  (PosX += 5)")
    print()
    cls_count = {}
    for r in refs:
        cls = r["type"]["class"]
        cls_count[cls] = cls_count.get(cls, 0) + 1
    print(f"  节点分类:")
    for cls, c in sorted(cls_count.items(), key=lambda x: -x[1]):
        print(f"    {cls}: {c}")


if __name__ == "__main__":
    main()
